// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXZeWEJkzRraOEFAiFKoN-SpZpMlSgvk',
    appId: '1:940025687222:web:9558ee82631f16d66f4a17',
    messagingSenderId: '940025687222',
    projectId: 'material-construcao-d4d93',
    authDomain: 'material-construcao-d4d93.firebaseapp.com',
    storageBucket: 'material-construcao-d4d93.firebasestorage.app',
    measurementId: 'G-WTGVYYT5BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoR3tT-8e-gbw0n04fzq7IlgSVnbSBIFo',
    appId: '1:940025687222:android:7b6ebbf18763d6b56f4a17',
    messagingSenderId: '940025687222',
    projectId: 'material-construcao-d4d93',
    storageBucket: 'material-construcao-d4d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJ1vJqBbeMWbiEpFH997KbeYd_6yxTTI',
    appId: '1:940025687222:ios:ba1362bde9c4a3496f4a17',
    messagingSenderId: '940025687222',
    projectId: 'material-construcao-d4d93',
    storageBucket: 'material-construcao-d4d93.firebasestorage.app',
    iosClientId: '940025687222-qe48lct9400p3hnf7k26asf7f7bb9far.apps.googleusercontent.com',
    iosBundleId: 'com.example.asiObra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJ1vJqBbeMWbiEpFH997KbeYd_6yxTTI',
    appId: '1:940025687222:ios:ba1362bde9c4a3496f4a17',
    messagingSenderId: '940025687222',
    projectId: 'material-construcao-d4d93',
    storageBucket: 'material-construcao-d4d93.firebasestorage.app',
    iosClientId: '940025687222-qe48lct9400p3hnf7k26asf7f7bb9far.apps.googleusercontent.com',
    iosBundleId: 'com.example.asiObra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGXZeWEJkzRraOEFAiFKoN-SpZpMlSgvk',
    appId: '1:940025687222:web:e4ce8230da9857916f4a17',
    messagingSenderId: '940025687222',
    projectId: 'material-construcao-d4d93',
    authDomain: 'material-construcao-d4d93.firebaseapp.com',
    storageBucket: 'material-construcao-d4d93.firebasestorage.app',
    measurementId: 'G-S4G68E0578',
  );
}
