// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qI5e8dco25kYDWRFcxVU0GGGMSfD078',
    appId: '1:35197657399:web:7103931aa07959148e3ab2',
    messagingSenderId: '35197657399',
    projectId: 'asiobra',
    authDomain: 'asiobra.firebaseapp.com',
    storageBucket: 'asiobra.firebasestorage.app',
    measurementId: 'G-LKH6LJ7H5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTa19LoWmry7dM_Ks-z_1DtO0h8sbOmro',
    appId: '1:35197657399:android:9e5f5f0af99ee9978e3ab2',
    messagingSenderId: '35197657399',
    projectId: 'asiobra',
    storageBucket: 'asiobra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBir4Gp2B_v3VfRUEJwaW5cwVBDhc34SXA',
    appId: '1:35197657399:ios:5fb9aaa1e9bcbbfd8e3ab2',
    messagingSenderId: '35197657399',
    projectId: 'asiobra',
    storageBucket: 'asiobra.firebasestorage.app',
    iosBundleId: 'com.example.asiObra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBir4Gp2B_v3VfRUEJwaW5cwVBDhc34SXA',
    appId: '1:35197657399:ios:5fb9aaa1e9bcbbfd8e3ab2',
    messagingSenderId: '35197657399',
    projectId: 'asiobra',
    storageBucket: 'asiobra.firebasestorage.app',
    iosBundleId: 'com.example.asiObra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8qI5e8dco25kYDWRFcxVU0GGGMSfD078',
    appId: '1:35197657399:web:fae1554905c193f08e3ab2',
    messagingSenderId: '35197657399',
    projectId: 'asiobra',
    authDomain: 'asiobra.firebaseapp.com',
    storageBucket: 'asiobra.firebasestorage.app',
    measurementId: 'G-MZBFZPNM94',
  );
}
